{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-infra.operatorName" . }}
  namespace: {{ include "agent-infra.namespace" . }}
  labels:
    {{- include "agent-infra.labels" . | nindent 4 }}
{{- end }}
